In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [26]:
from sklearn.preprocessing import scale 

In [27]:
os.chdir(r'C:\Users\Carlos\Desktop\AML')

In [28]:
df = pd.read_csv(r'weight.csv',sep=';')

In [29]:
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [30]:

X1 = df['Weight']
Y1 = df['Height']
n = len(Y1)

In [31]:
x =scale(X1)
y =scale(Y1)

In [32]:
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size=0.3)

In [33]:
def DesignMat(x):
    n = len(x)
    X = np.c_[np.ones(n),x]
    return (X)
DesignMat(x)

array([[ 1.        ,  2.50579697],
       [ 1.        ,  0.02710064],
       [ 1.        ,  1.59780623],
       ...,
       [ 1.        , -1.02672965],
       [ 1.        ,  0.07512745],
       [ 1.        , -1.48850724]])

In [34]:
DesignMat(x_train)

array([[ 1.        , -1.44558403],
       [ 1.        , -0.99253488],
       [ 1.        , -0.21941535],
       ...,
       [ 1.        ,  0.5053117 ],
       [ 1.        ,  0.6385233 ],
       [ 1.        , -1.1426533 ]])

In [35]:
x_train = DesignMat(x_train)
x_test = DesignMat(x_test)

In [36]:
weights = np.linalg.inv(x_train.T.dot(x_train)).dot(x_train.T).dot(y_train)
weights

array([0.00100386, 0.92489201])

In [37]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))
    

In [38]:
def deriv_sigmoid(x):
    return(sigmoid(x) * (1 - sigmoid(x)))

In [39]:
hidden_sum = weights[0] +weights[1]*x_train

In [40]:
hidden_output = sigmoid(hidden_sum)
hidden_output

array([[0.71624191, 0.20816776],
       [0.71624191, 0.28557288],
       [0.71624191, 0.44968793],
       ...,
       [0.71624191, 0.61499614],
       [0.71624191, 0.64372506],
       [0.71624191, 0.25810772]])

In [41]:
u21 = np.linalg.inv(x_test.T.dot(x_test)).dot(x_test.T).dot(y_test)
u21

array([-0.00235293,  0.92438058])

In [57]:
def negative_loglikelihood(x_train,y_train,weights):
    J = np.sum(-y * x_train * weights) + np.sum(np.exp(x_train.weights)) + np.sum(np.log(y))
    return J

In [43]:
def deriv_w0(x_train,y_train,y_test,n):
    return (-1/n)*sum(y_train - y_test)

In [44]:
def deriv_w1(x_train,y_train,y_test,n):
    return (-1/n)*sum((y_train - y_test)*x_train)

In [65]:
epochs = 1000
learn_rate = 0.01
cost = []
weight = []



for i in range(epochs):
    y_pred = u21
    negative_loglikelihood(x_train,x_test,y_pred)
    cost.append(u2l)
    
    weights = weights - (learn_rate*(1/n)*sum(y_pred - y_train))
    weights.append[weights]
        
  

    
print(weights[0])
print(weights[1])
print(cost)
print(weights)

ValueError: operands could not be broadcast together with shapes (10000,) (7000,2) 